### ISSUE TITLE
"ERROR (code 3): Internal Service Error. Please report this error by opening an issue on GitHub."

### ISSUE THREAD

**Issue by WildEgo** [supergrecko/RiotQuest#44]
**Describe the bug**
I really don't have a good explanation the request is just not created I'd suppose

**To Reproduce**
1. use RiotQuest\Client as LeagueAPI;
2. return LeagueAPI::summoner(strtolower($result->server))->name($result->account_ign);
3. "ERROR (code 3): Internal Service Error. Please report this error by opening an issue on GitHub."

**Expected behavior**
Should've returned anything that is not an error

**Desktop (please complete the following information):**
 - OS: Windows 10
 - PHP Version: 7.2.10
 - RiotQuest Version: ^1.3

**Additional context**
Should be manifest.json related

**Comment by supergrecko** [comment]
It looks like something has been changed on the API. I'll investigate the issue and publish a fix.

**Comment by WildEgo** [comment]
> It looks like something has been changed on the API. I'll investigate the issue and publish a fix.

really appreciate it man good job on the package, keep us updated

**Comment by supergrecko** [comment]
The issue should be resolved now. If you bump into it again open another issue and I'll have another look.

I believe the cause was that the Riot API's Shard status response object had changed. It now has a heading inside MessageDTO which was not documented on the Riot API site.

I have released the patch under the tag `1.3.1`.
